# Ground-Filtered Mapping Configuration
# Aggressive ground filtering to prevent ground from being marked as obstacles

/**:
  ros__parameters:
    # Subscription topics
    subscribe_rgb: False
    subscribe_depth: False
    subscribe_rgbd: False
    subscribe_stereo: False
    subscribe_scan: False
    subscribe_scan_cloud: True
    subscribe_user_data: False
    subscribe_odom_info: False
    wait_imu_to_init: False
    
    # Frame configuration
    frame_id: base_link
    map_frame_id: map
    odom_frame_id: odom
    publish_tf: True
    
    # Database and memory management
    Mem/IncrementalMemory: 'true'
    Mem/InitWMWithAllNodes: 'false'
    
    # Disable database saving
    database_path: ''
    Db/TargetVersion: ''
    
    # RTAB-Map core parameters
    Rtabmap/DetectionRate: '2.0'  # Increased from 1.0 - process more frames per second
    Rtabmap/TimeThr: '0'
    Rtabmap/LoopThr: '0.11'
    Rtabmap/CreateIntermediateNodes: 'true'
    
    # Memory management
    Mem/NotLinkedNodesKept: 'false'
    Mem/STMSize: '50'  # Increased from 30 - keep more nodes in short-term memory
    Mem/LaserScanDownsampleStepSize: '1'
    
    # 2D Grid map generation - AGGRESSIVE GROUND FILTERING
    Grid/FromDepth: 'false'
    Grid/3D: 'false'
    Grid/CellSize: '0.05'
    Grid/RangeMin: '0.3'     # Reduced from 0.5 to capture closer points
    Grid/RangeMax: '15.0'    # Increased from 10.0 to map larger areas
    
    # Ground filtering - Key parameters to prevent ground as obstacles
    Grid/GroundIsObstacle: 'false'  # CRITICAL: Ground is NOT an obstacle
    Grid/MinGroundHeight: '-0.3'    # Accept ground points from -30cm
    Grid/MaxGroundHeight: '0.4'     # to +40cm as ground (not obstacles)
    Grid/MaxObstacleHeight: '4.0'   # Only points above 20cm are potential obstacles
    Grid/MinObstacleHeight: '0.5'   # Minimum height for obstacles (same as max ground)
    
    # Normal-based segmentation for better ground detection
    Grid/NormalsSegmentation: 'true'
    Grid/MaxGroundAngle: '20.0'     # Allow up to 20 degree slopes as ground
    Grid/NormalK: '20'              # Neighbors for normal estimation
    Grid/ClusterRadius: '0.15'
    
    # Noise filtering
    Grid/NoiseFilteringRadius: '0.1'
    Grid/NoiseFilteringMinNeighbors: '5'
    Grid/PreVoxelFiltering: 'true'
    Grid/DepthDecimation: '1'
    
    # Ray tracing for free space
    Grid/RayTracing: 'true'
    Grid/FootprintLength: '0.0'     # Don't add robot footprint
    Grid/FootprintWidth: '0.0'
    Grid/FootprintHeight: '0.0'
    
    # Flat obstacle detection
    Grid/FlatObstacleDetected: 'true'
    
    # Optimization
    RGBD/OptimizeFromGraphEnd: 'false'
    RGBD/OptimizeMaxError: '0.0'
    Optimizer/Strategy: '0'
    Optimizer/Iterations: '100'
    Optimizer/Epsilon: '0.00001'
    
    # Point cloud processing
    ICP/MaxCorrespondenceDistance: '0.15'  # Increased from 0.1 - match points further apart
    ICP/PointToPlane: 'true'
    ICP/Iterations: '30'
    ICP/Epsilon: '0.001'
    ICP/MaxTranslation: '0.5'  # Increased from 0.3 - allow larger movements
    ICP/MaxRotation: '1.0'     # Increased from 0.78 (~45° to ~57°)
    ICP/VoxelSize: '0.03'      # Decreased from 0.05 - better point cloud quality
    ICP/DownsamplingStep: '1'
    
    # Visual features (disabled)
    Vis/MinInliers: '15'
    Vis/MaxFeatures: '0'
    
    # Loop closure
    RGBD/ProximityBySpace: 'true'
    RGBD/ProximityMaxGraphDepth: '100'  # Increased from 50 - larger search area
    RGBD/ProximityPathMaxNeighbors: '20'  # Increased from 10 - more connections
    RGBD/AngularUpdate: '0.05'  # Increased from 0.01 - update less frequently for larger steps
    RGBD/LinearUpdate: '0.05'   # Increased from 0.01 - update every 5cm instead of 1cm
    RGBD/LocalRadius: '10.0'    # Increased from 5.0 - larger local map area
    
    # Publishing
    map_always_update: True
    map_empty_ray_tracing: True
